### PR TITLE
Unified error/result using thiserror

### PR DESCRIPTION
**Pull request by fpagliughi**
Created a unified `Error` and `Result` type for the library using `thiserror`. It wraps errors from io, mqtt, json, etc.

### CODE REVIEW

**Comment by cecton** [comment]
Not that I mind defining more precisely the errors but since they all work with io::Error, I don't see much the point of giving such granularity. Especially since the errors are mostly giving a proper meaningful text string with it

**Comment by fpagliughi** [comment]
The intent was somewhat practical:
1. So we could return openssl errors from `Client::get_password()`, instead of unwrap()'ing them
2. So we could return JSON parsing errors from the `Discovery` iterator. (This would have helped find the 890 discovery problem sooner).
3. There may be more/different libraries and errors as we go, and it could break apps if the library adds or changes error types.
4. If an app or library that uses this code also wants to wrap errors, it's much easier if this library just has one error type to manage. Just look at openssl which has multiple different types of errors. It's painful to deal with!

**Comment by cecton** [comment]
ahh, I forgot to replace all those unwrap! :sweat_smile:  ok thanks!!

**Comment by cecton** [comment]
Ok I replaced the unwraps... but in the end, most errors can be converted to io::Error so I actually did not make an error type yet. I think it's fine as it but if you prefer a clean enum error don't hesitate to change directly on master (don't make PR unless you really want my opinion). Please do everything as you think is best

**Pull request closed without merging**
