### PR TITLE
List supported devices in the README

### PR DESCRIPTION
**Pull request by cecton**

### CODE REVIEW

**Comment by cecton** [comment]
@VictorKoenders @fpagliughi maybe it would be a good idea now that we support a few devices to list them. Can you give me your model of roomba?

**Comment by VictorKoenders** [comment]
Haven't fully tested my roomba through yet but I added my model (966)

**Comment by fpagliughi** [comment]
I haven’t gotten mine to work yet (see #9), but if I do, I will update the read email.

**Comment by cecton** [comment]
Good enough for now. If there is anything special to do for your model you can mention it in the README

**Pull request merged**
